version: "3.7"

services:
  postgres:
    container_name: django-postgres
    image: postgres
    restart: unless-stopped
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: django-pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5500:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@django.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  # backend:
  #   build: ./backend/
  #   container_name: django-backend
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8080:80"



volumes:
  postgres-data:
  pgadmin-data:
