# Generated by Django 3.2.3 on 2024-06-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
